name: flutterlens
description: A modern visual inspector for Flutter.
version: 0.1.0-dev.1
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.1'

flutter:
  uses-material-design: true

dependencies:
  devtools_app_shared: ^0.5.1
  devtools_extensions: ^0.5.1
  flutter:
    sdk: flutter
  flutterlens_core:
    path: ../flutterlens_core
  flutterlens_ui:
    path: ../flutterlens_ui

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
